AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"

Style/Documentation:
  Exclude:
    - "spec/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"